### ISSUE TITLE
会員管理 メールアドレス確認機能の追加

### ISSUE THREAD

**Issue by morisatoru** [NIFCLOUD-mbaas/ncmb_swift#10]
## 概要

* 会員管理機能にてメールアドレス確認を行えるようにする。

**Comment by ncmbadmin** [comment]
以下のようにメール認証機能は対応していますが、
こちらのissueの未対応機能は具体的に確認します
https://mbaas.nifcloud.com/doc/current/user/authorize_email_swift.html#gsc.tab=0

**Comment by morisatoru** [comment]
会員登録メール要求API `requestMailAddressUserEntry` について実装されていることを確認。

メールアドレス確認API `mailAddressConfirm` については SDK が直接利用するものではないため、実装から除外する。

結論として issue の概要は満たされていると判断する。
