### ISSUE TITLE
プッシュ通知 開封確認用機能の追加

### ISSUE THREAD

**Issue by morisatoru** [NIFCLOUD-mbaas/ncmb_swift#11]
## 概要

* プッシュ通知機能に開封確認用の機能を追加する。

**Comment by morisatoru** [comment]
`NCMBAnalytics` について、内部の実装を `service` サブグループへ移動するなど変更を行う。

**Comment by ncmbadmin** [comment]
本件、以下のドキュメントのように、対応済みのため、本issueをクローズします。
https://mbaas.nifcloud.com/doc/current/push/openrates_swift.html
