### ISSUE TITLE
NCMBFileのQuery返り値が空のNCMBFileになっている

### ISSUE THREAD

**Issue by goofmint** [NIFCLOUD-mbaas/ncmb_swift#132]
## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version)
1.4

- Xcode 14.3.1

NCMBFileのQueryを実行してもファイル名が空です。

```swift
var query: NCMBQuery<NCMBFile> = NCMBFile.query
query.where(field: "fileName", toMatchPattern: ".*.m4a$")
let results = query.find()
if case let .success(ary) = results {
    print("->" + ary[0].fileName)
}
```

本来NCMBFile.initが呼ばれるはずが、NCMBBase.initに移動している模様

原因が同じだとすれば、User/Installation/Push/Roleなどでも同じことが起こっている可能性があります。

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございます。
順次、優先付けを行ったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。

対応次第、こちらの issue にて報告いたします。
どうぞよろしくお願いいたします。

**Comment by harapekokoro** [comment]
お世話になっております。
本 issue の 改修が完了し v1.4.1 にてリリース済みです。
ご報告ありがとうございました。

改修済みのSDKは以下のリリースページにてご確認ください。
https://github.com/NIFCLOUD-mbaas/ncmb_swift/releases/tag/v1.4.1

今後とも、mobile backend をどうぞよろしくお願いいたします。
