### ISSUE TITLE
【新機能検討】AppleID連携対応

### ISSUE THREAD

**Issue by ncmbadmin** [NIFCLOUD-mbaas/ncmb_swift#57]
### 概要

mobile backendのSNS連携機能は現在Facebook, twitter, googleIDのログイン連携を対応しております。Apple IDログイン連携機能をSwift SDKで利用できるように検討をします。

- ※参考：
AppleIDについて
https://help.apple.com/developer-account/?lang=en#/devde676e696

**Comment by kobayashi-masaya** [comment]
v1.1.0リリースにて対応済みのためclose致します。
