### ISSUE TITLE
podspecのlintでエラー

### ISSUE THREAD

**Issue by novr** [NIFCLOUD-mbaas/ncmb_swift#86]
SDKの改善にご協力いただきありがとうございます。  
(Thank you for your support our SDK.)

SDKの不具合を報告する場合は、以下の項目を確認してください。  
(If you want to report a bug of the SDK, please confirm the following terms.)

- サンプルコードにAPIキーや個人情報が含まれていないか (The sample code does not include credential information?)
- 同じバグをすでに誰かが報告していてOpenになっているissueはないか (This bug is not being reported?)

## 不具合の概要(Description of bug)

NCMB.podspecのlintでエラーが発生します

- SDKのバージョン(SDK version)

NCMB (1.1.2)

- 不具合が発生した環境(Environment requirement)

CocoaPods: 1.9.3

- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)

❯ pod spec lint

- エラーメッセージ(Error messages)

 -> NCMB (1.1.2)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/local/bin/git clone https://github.com/NIFCloud-mbaas/ncmb_ios.git /var/folders/k7/np3t6grj2ll7d8rf6v_ng_r88yprg8/T/d20201210-72665-dbqmzw --template= --single-branch --depth 1 --branch v1.1.2

Cloning into '/var/folders/k7/np3t6grj2ll7d8rf6v_ng_r88yprg8/T/d20201210-72665-dbqmzw'...
warning: Could not find remote branch v1.1.2 to clone.
fatal: Remote branch v1.1.2 not found in upstream origin
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございます。

順次、優先付けを行ったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend をどうぞよろしくお願いいたします。
