### ISSUE TITLE
onChangeでは初期化のタイミングが遅いかも知れません

### ISSUE THREAD

**Issue by goofmint** [NIFCLOUD-mbaas/ncmb_swift#94]
公式のドキュメントでは、onChangeにてNCMBの初期化処理を行うように書かれています。

https://mbaas.nifcloud.com/doc/current/tutorial/quickstart_swift_ui.html#API%E3%82%AD%E3%83%BC%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%A8SDK%E3%81%AE%E5%88%9D%E6%9C%9F%E5%8C%96

```swift
@main
struct SwiftApp: App {
    @Environment(\.scenePhase) var scenePhase
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
        .onChange(of: scenePhase) { scene in
            switch scene {
            case .active:
                // APIキーの設定とSDK初期化
                NCMB.initialize(applicationKey: "YOUR_APPLICATION_KEY", clientKey: "YOUR_CLIENT_KEY")
                // ↓　ここにサンプルコードを実装　↓

            case .background:
                print("App is in background")
            case .inactive:
                print("App is inactive")
            @unknown default:
                print("default")
            }
        }
    }
}
```

Swift5では問題なかったのですが、Swift5.5で試したところ、他のViewのonAppearが先に呼ばれるようです。そのため、別なViewでonAppearを使ってデータストアへアクセスすると、emptyApplicationKeyエラーが発生します。

こちらもonAppearへ移した方が良いのかも知れません。ただ、それに伴う弊害は分かっていません…。

```swift
@main
struct SwiftApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
              .onAppear() {
                  // APIキーの設定とSDK初期化
                  NCMB.initialize(applicationKey: "YOUR_APPLICATION_KEY", clientKey: "YOUR_CLIENT_KEY")
              }
        }
    }
}
```

**Comment by ncmbadmin** [comment]
@goofmint 
お世話になっております。ご報告ありがとうございました。
本 issue にていただいたフィードバックを参考にさせていただき、ドキュメントを更新いたしました。

更新済みのドキュメントは以下のページにてご確認ください。
[APIキーの設定とSDKの初期化 (Swift UIバージョン)](https://mbaas.nifcloud.com/doc/current/tutorial/quickstart_swift_ui.html#API%E3%82%AD%E3%83%BC%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%A8SDK%E3%81%AE%E5%88%9D%E6%9C%9F%E5%8C%96)
今後とも、mobile backend をどうぞよろしくお願いいたします。

**Comment by goofmint** [comment]
↓ だけで良いかと思うのですが既存の onChange や `var windows: UIWindow?` がある理由は何でしょうか？何かあるなら良いのですが、コード量が増えると複雑に見えてしまいます。

```swift
@main
struct NCMBDemoApp: App {
    init() {
        // APIキーの設定とSDK初期化
        NCMB.initialize(applicationKey: "YOUR_APPLICATION_KEY", clientKey: "YOUR_CLIENT_KEY")
    }
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

**Comment by ncmbadmin** [comment]
早速ご確認いただき、ありがとうございます。
上記のフィードバック、ありがとうございました。
ドキュメントの改善にぜひ参考させていただきます。
対応次第、こちらの issue にて報告いたします。

**Comment by ncmbadmin** [comment]
お世話になっております。
本件、いただいたフィードバックをドキュメントに反映いたしました。
更新済みのドキュメントは以下のページにてご確認ください。
[APIキーの設定とSDKの初期化 (Swift UIバージョン)](https://mbaas.nifcloud.com/doc/current/tutorial/quickstart_swift_ui.html#API%E3%82%AD%E3%83%BC%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%A8SDK%E3%81%AE%E5%88%9D%E6%9C%9F%E5%8C%96)
こちら対応完了といたし、issueをクローズいたします。
また何かありましたらご連絡ください。
今後とも、mobile backend をどうぞよろしくお願いいたします。
